ASBDB="CASTORE1"
ASBSCHEMA="CAUSER"
ASBDBUSER="db2inst1"
ASBUSER="dasusr1"
db2 "CONNECT TO $ASBDB" USER $ASBDBUSER
DBTABLES=`db2 -x "SELECT tabname FROM syscat.tables WHERE tabschema=UPPER('$ASBSCHEMA')"`

for TABLENAME in $DBTABLES;
do db2 "GRANT SELECT ON $ASBSCHEMA.$TABLENAME TO USER $ASBUSER"
done
db2 "DISCONNECT $ASBDB"
